name: Publish Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --ignore-engines
      - name: Publish
        run: |
          yarn cleanPublish --without-publish --temp-dir package
          yarn publish --non-interactive package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
